require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/assemblies_parts", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # AssembliesPart. As you add validations to AssembliesPart, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      AssembliesPart.create! valid_attributes
      get assemblies_parts_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      assemblies_part = AssembliesPart.create! valid_attributes
      get assemblies_part_url(assemblies_part)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_assemblies_part_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      assemblies_part = AssembliesPart.create! valid_attributes
      get edit_assemblies_part_url(assemblies_part)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new AssembliesPart" do
        expect {
          post assemblies_parts_url, params: { assemblies_part: valid_attributes }
        }.to change(AssembliesPart, :count).by(1)
      end

      it "redirects to the created assemblies_part" do
        post assemblies_parts_url, params: { assemblies_part: valid_attributes }
        expect(response).to redirect_to(assemblies_part_url(AssembliesPart.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new AssembliesPart" do
        expect {
          post assemblies_parts_url, params: { assemblies_part: invalid_attributes }
        }.to change(AssembliesPart, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post assemblies_parts_url, params: { assemblies_part: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested assemblies_part" do
        assemblies_part = AssembliesPart.create! valid_attributes
        patch assemblies_part_url(assemblies_part), params: { assemblies_part: new_attributes }
        assemblies_part.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the assemblies_part" do
        assemblies_part = AssembliesPart.create! valid_attributes
        patch assemblies_part_url(assemblies_part), params: { assemblies_part: new_attributes }
        assemblies_part.reload
        expect(response).to redirect_to(assemblies_part_url(assemblies_part))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        assemblies_part = AssembliesPart.create! valid_attributes
        patch assemblies_part_url(assemblies_part), params: { assemblies_part: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested assemblies_part" do
      assemblies_part = AssembliesPart.create! valid_attributes
      expect {
        delete assemblies_part_url(assemblies_part)
      }.to change(AssembliesPart, :count).by(-1)
    end

    it "redirects to the assemblies_parts list" do
      assemblies_part = AssembliesPart.create! valid_attributes
      delete assemblies_part_url(assemblies_part)
      expect(response).to redirect_to(assemblies_parts_url)
    end
  end
end
