
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: teste_livraria_development
  username: postgres
  password: postgres
  host: localhost
  port: 5432

test:
  <<: *default
  database: teste_livraria_test
  username: postgres
  password: postgres
  host: localhost
  port: 5432

production:
  <<: *default
  database: teste_livraria_production
  username: teste_livraria
  password: <%= ENV["TESTE_LIVRARIA_DATABASE_PASSWORD"] %>
